### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by josmithua** [adrai/next-static-i18n-test#1]
i18n was an afterthought in a company website, and so there are a lot of links in the wild with no locale in the url: `https://site.com/about`

Is it possible to use i18n in the way from this repo with links like `https://site.com/about` defaulting or redirecting to a default language (english), and links like `https://site.com/fr/about` to use the locale in the URL (french)?

I've cloned this repo and did some quick tests: `http://localhost:3000` redirects to `http://localhost:3000/en`, but `http://localhost:3000/second-page` doesn't.

**Comment by adrai** [comment]
Just tested it, seems to work: https://github.com/adrai/next-static-i18n-test/commit/7192d3c92b7db874454ae02823d93d6628d775c9
